# Generated by Django 5.1.2 on 2024-10-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleBuddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('minister', 'Minister'), ('user', 'User'), ('schedule_creator', 'Schedule Creator')], default='user', max_length=20),
        ),
    ]
