# Generated by Django 5.1.2 on 2024-11-06 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleBuddy', '0003_ministry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ScheduleBuddy.ministry')),
            ],
        ),
    ]
