# Generated by Django 5.1.2 on 2024-11-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleBuddy', '0004_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='assign_with_others',
            field=models.BooleanField(default=False),
        ),
    ]
